### ISSUE TITLE
cannot match pattern

### ISSUE THREAD

**Issue by lucek4** [Warehousing/Warehousing#101]
Nie można załadować modyfikacji "Warehousing": Mod Warehousing version {{VERSION}} not matching pattern "Major.Middle.Minor".

**Comment by dgw** [comment]
If you are trying to load the mod directly, that isn't supported. `{{VERSION}}` is a placeholder that gets filled in with the real version number during the build process; see [Makefile](https://github.com/Warehousing/Warehousing/blob/master/Makefile).
