### ISSUE TITLE
Should not be buildable on space platform in Space Age

### ISSUE THREAD

**Issue by yuyaryshev** [Warehousing/Warehousing#103]
Should not be buildable on space platform in 2.0.

Because all the idea of space platform is very limited space - chests can't be built there. So warehouses seem to be very inconsistent with that fact.

... or at least should be a setting to prevent building in space, which should be off by default.

**Comment by Anoyomouse** [comment]
Space age does some weird things to chests apparently, so i've done the same thing here

**Comment by ThatoneWeeb1121** [comment]
I think it should be a togglable option tbh, completely removing it for those who may be mid-playthrough seems kinda cruel.

**Comment by dgw** [comment]
@ThatoneWeeb1121 It was never supposed to be allowed. It was a bug.
