### ISSUE TITLE
Warehouses require Iron Sticks which is not an unlocked intermediate

### ISSUE THREAD

**Issue by PiggyWhiskey** [Warehousing/Warehousing#106]
Space Age (or possibly 2.0 in general) changed Iron Sticks to not be unlocked from early, and requires a technology (Circuit Network, Concrete, Power Poles 1, Railway)

As warehousing may be unlocked before these, they're not usable without the Iron Stick Recipe.

Recommend adding the Iron Stick recipe to the Warehouse technology to allow them to be crafted without other technology requirements

**Comment by dgw** [comment]
Seems to be a 2.0 change, but not one specifically listed in [the item](https://wiki.factorio.com/Iron_stick)'s version history. [This is when](https://wiki.factorio.com/index.php?title=Infobox:Iron_stick&diff=201523&oldid=171805) the required technologies were added to its infobox, about two weeks ago. (No doubt there is a backlog of wiki edits to be made after a huge update like that…)

This change is kind of annoying. I'd like to make _any_ of the techs that unlocks the iron stick recipe unlock researching warehouses, but the `prerequisites` field doesn't support it. You can only specify a simple list of technologies, _all_ of which must be researched to enable researching the tech they're attached to.

Given the tech tree limitations, I would lean toward replacing the sticks with something else. Maybe iron chests, to imply boxes stacked on shelves inside the building? Depending on the number of chests, steel cost could be adjusted.

**Comment by PiggyWhiskey** [comment]
Iron chests would function well.

It feels like a terrible hack to add that intermediate to every tier 1 tech that starts to need it

**Comment by dgw** [comment]
> It feels like a terrible hack to add that intermediate to every tier 1 tech that starts to need it

I was surprised at seeing that the base game just… added `iron-stick` as an unlock for like 4 different techs.

Eliminating an item from the recipes felt like a good opportunity to take another look at the overall recipe "feel", so I put up #107 with more than just a swap to iron-chest.
