### ISSUE TITLE
Missing `item_sounds` global in Factorio 2.0.16

### ISSUE THREAD

**Issue by SGZ-Creations** [Warehousing/Warehousing#115]
Failed to load mods: __Warehousing__/prototypes/item.lua:17: attempt to index global 'item_sounds' (a nil value)
stack traceback:
	__Warehousing__/prototypes/item.lua:17: in main chunk
	[C]: in function 'require'
	__Warehousing__/data.lua:6: in main chunk

![image](https://github.com/user-attachments/assets/28be25b2-0ebc-4411-8cf0-9af7a77c5b72)

**Comment by dgw** [comment]
Thanks for reporting. I will fold #116 into the Warehousing 1.0.1 update we were already planning to release this weekend.
