### ISSUE TITLE
New Logistics Requests system

### ISSUE THREAD

**Issue by Jivaii** [Warehousing/Warehousing#119]
With the 2.0 update, we can have "sections" for various pre-set logistics requests, as well as a toggle for "Trash Unrequested" that auto-trashes anything over request. On normal vanilla logistics chests (requesters and buffers), there's two rows of trash slots, but the requester/buffer storehouse and warehouse don't have that. Would it be possible to get this functionality in those?

**Comment by dgw** [comment]
_Implementation notes: If we do this, it will use [the `trash_inventory_size` property](https://lua-api.factorio.com/2.0.17/prototypes/LogisticContainerPrototype.html#trash_inventory_size), flagged as "new" in 2.x. Its value is `0` by default; Factorio's built-in [`requester`](https://github.com/wube/factorio-data/blob/2d4e9820482bcca1a1424f87b785676a7ada3129/base/prototypes/entity/entities.lua#L5900-L5901) and [`buffer`](https://github.com/wube/factorio-data/blob/2d4e9820482bcca1a1424f87b785676a7ada3129/base/prototypes/entity/entities.lua#L5839-L5840) chests set it to `20`._

**Comment by mike1000195** [comment]
what does that even mean?

**Comment by dgw** [comment]
They're notes for _us_, so we don't have to go look up the technical stuff again if/when we add this feature.

At the moment I would like to figure out a way to leave more space in the warehouse GUI for logistics, before we commit to a feature like this that would add _more_ stuff to an already very small area of the window. I don't know if mods can affect how the built-in GUI layout works but we can certainly try…

**Comment by dgw** [comment]
> I don't know if mods can affect how the built-in GUI layout works

It seems not, at least not according to the docs and old forum threads I've reviewed.

Went ahead and opened #124 to add this feature. In the end, it isn't _that_ bad in the GUIs (see sample screenshots in the PR)—at least not if you are using a decently sized screen.
