### ISSUE TITLE
HR pictures

### ISSUE THREAD

**Issue by Kamsta99** [Warehousing/Warehousing#74]
Hi i upscaled and tweaked pictures and also modified you mod to use my new HR sprites. I do not want to be selfish, so i sharing this with you. Use if you want
[entity.zip](https://github.com/Warehousing/Warehousing/files/3050036/entity.zip)
If you can credit me in changelog for my hard work

**Comment by dgw** [comment]
New graphics are in process (#51), so I don't think it's worth making a release with these. When the redesigned warehouses are ready, @Nova-Kast will almost certainly generate the sprites in HD.
