### ISSUE TITLE
Crash on load 0.17.43, warehouse-buffer.png

### ISSUE THREAD

**Issue by Shinhan** [Warehousing/Warehousing#75]
Factorio version 0.17.43
Warehousing version 0.2.3

Worked fine on earlier versions. Today, when starting the game I get the error loading mods:

Failed to load mods: Closing file __Warehousing__/graphics/entity/warehouse-buffer.png failed (-105): __Warehousing__/graphics/entity/warehouse-buffer.png

**Comment by Shinhan** [comment]
Nvm, after deleting and reainstalling the mod it works again.

**Comment by dgw** [comment]
I was _just_ getting ready to test this and see if I could reproduce, but I'm glad it was just a corrupted mod file download. Having kept up with the changelogs, I was at a loss as to how .43 could have broken this.

**Comment by dgw** [comment]
Guessing that [this bug report](https://forums.factorio.com/71451) (fixed today in Factorio 0.17.46) is the same or a closely related issue.
