### ISSUE TITLE
Issue on mod load

### ISSUE THREAD

**Issue by Marsilox** [Warehousing/Warehousing#80]
Hi,
when i try to launch factorio this error is thrown: 
"Failes to load mod "Warehousing": Mod Warehousing version {{VERSION}} not matching pattern "Major.Middle.Minor""

**Comment by wbeever** [comment]
Not a solution, may help with troubleshooting?  

I changed {{VERSION}} to 0.3.1 in info.json, now it reads 

"Failes to load mod "Warehousing": Mod Warehousing version 0.3.1 not matching pattern "Major.Middle.Minor""

**Comment by dgw** [comment]
Sounds like you were trying to load the mod without making it first.

Using the mod directly from source is unsupported. Please download a ZIP from releases or the Factorio mod portal.
