### ISSUE TITLE
Enderwarehouse?

### ISSUE THREAD

**Issue by someone-somenet-org** [Warehousing/Warehousing#85]
With 1.1 wube added "Enderchests", or "linked chest" as they named it.

Would it be possible to get an "Enderwarehouse"?
Possibly not reseachable/constructable, but still there so it could be used in editor-mode?

Its defined here: ``./data/base/prototypes/entity/entities.lua:15766:linked_chest.name = "linked-chest"``

**Comment by dgw** [comment]
Even if only usable in editor mode, it would need graphics (entity, icon). Presumably if a "linked warehouse" existed, somebody would want a "linked storehouse" too later.

If you really want it, sooner than $WHEN_NEW_GRAPHICS_ARE_DONE, I'd ask that you create the necessary sprites & icons for how you'd want it to look in-game.

**Comment by someone-somenet-org** [comment]
I am really bad at graphics ... The vanilla linked chest is a white logistic chest...
**``Behold my epic GIMP skills!``**

![storehouse-linked](https://user-images.githubusercontent.com/5354356/104528586-f7f94380-5607-11eb-9c09-e2fbc888b4b7.png)
![warehouse-linked](https://user-images.githubusercontent.com/5354356/104528588-f891da00-5607-11eb-9782-f32f885e7ca9.png)
![storehouse-linked (1)](https://user-images.githubusercontent.com/5354356/104528589-f92a7080-5607-11eb-8c64-3f8058b0cb5f.png)
![warehouse-linked (1)](https://user-images.githubusercontent.com/5354356/104528590-f92a7080-5607-11eb-8b68-dd70ef6626b2.png)

**Comment by dgw** [comment]
See #87.
