### ISSUE TITLE
Power Satisfaction.

### ISSUE THREAD

**Issue by roughtoast** [Warehousing/Warehousing#93]
Attempting to make a massive Green Circuit farm how ever i cant get anywhere near peak efficiency due to power issue.
outside factory power satisfation im making around 50ghz alown with 50 ghz extra accumulator storage. so outside satisfaction is hardly used.
Screenshots bellow I would love to see full power passthrough if possible. or at least be able to hook up extra lines to the factories to select how you want your power to be split up.

https://imgur.com/a/ya4oxSl

**Comment by roughtoast** [comment]
Attempting to make a massive Green Circuit farm how ever i cant get anywhere near peak efficiency due to power issue.
outside factory power satisfation im making around 50ghz alown with 50 ghz extra accumulator storage. so outside satisfaction is hardly used.
Screenshots bellow I would love to see full power passthrough if possible. or at least be able to hook up extra lines to the factories to select how you want your power to be split up.

https://imgur.com/a/ya4oxSl

it also apears that the power does not work for accumulators. with or without it being a mod accumulator.

Code you may be after 
    energy_usage = "1.2KW",
    source_inventory_size = 1,
    energy_source =
    {
		type = "electric",
		usage_priority = "secondary-input",
    }
    

Sorry, just realiesed. commenting on wrong mod. -_- fml lol

**Comment by dgw** [comment]
> Sorry, just realiesed. commenting on wrong mod. -_-

That's just fine by me. I was wondering if I'd gone nuts, because I couldn't figure out what this issue had to do with warehouses. 😂
